### ISSUE TITLE
Support for React 17.x

### ISSUE THREAD

**Issue by reinier-millo** [metonym/react-fuzzy-highlighter#100]
Could give support for React 17.x. I'm using with react 17.x but must install deps with --force.

**Comment by reinier-millo** [comment]
Can check it https://github.com/reinier-millo/react-fuzzy-highlighter

**Comment by metonym** [comment]
What specifically is causing the install error? Is it because [`peerDeps`](https://github.com/metonym/react-fuzzy-highlighter/blob/8f2102c7ace56e7989257a32a0067c301bb3e68a/package.json#L21-L24) is specified? I don't see any harm in removing that.

**Comment by KevinKoetz** [comment]
Yes, it's because of peerDeps.

```bash
npm ERR! While resolving: react-fuzzy-highlighter@1.0.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR!   peer react@"^16 || ^17 || ^18" from @headlessui/react@1.3.0
npm ERR!   node_modules/@headlessui/react
npm ERR!     @headlessui/react@"1.3.0" from the root project
npm ERR!   16 more (@heroicons/react, @next/react-dev-overlay, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.x" from react-fuzzy-highlighter@1.0.0
npm ERR! node_modules/react-fuzzy-highlighter
npm ERR!   react-fuzzy-highlighter@"1.0.0" from the root project
```

**Comment by metonym** [comment]
`peerDependencies` has been removed in version 1.1.1.
