### ISSUE TITLE
bump fuse.js to latest version

### ISSUE THREAD

**Issue by amilajack** [metonym/react-fuzzy-highlighter#78]
I see that the version of fuse.js that this projcet uses is 3.x.x, which is far behind the current latest semver of 6.x.x. @metonym I'm interesting in creating a PR to update this package to use the latest version. Would that be a welcome change?

**Comment by metonym** [comment]
Yes, PRs are welcome.

**Comment by metonym** [comment]
Published [v1.0.0 to NPM](https://www.npmjs.com/package/react-fuzzy-highlighter).
